"""Create Cart

Revision ID: 3e70edd22b2b
Revises: 57188e193497
Create Date: 2026-09-16 21:06:49.404399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e70edd22b2b'
down_revision: Union[str, Sequence[str], None] = '57188e193497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Уникальный идентификатор владельца корзины из таблицы users'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Уникальный идентификатор продукта из таблицы product'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество единиц одного товара в корзине'),
    sa.Column('created_add', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Метка времени создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Метка времени последнего обновления записи'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_cart_items_user_product')
    )
    op.create_index(op.f('ix_cart_item_product_id'), 'cart_item', ['product_id'], unique=False)
    op.create_index(op.f('ix_cart_item_user_id'), 'cart_item', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_item_user_id'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_product_id'), table_name='cart_item')
    op.drop_table('cart_item')
    # ### end Alembic commands ###
