"""Update column 'rating' in table Product 3

Revision ID: 656467a3bbd1
Revises: 0ad174b21dfb
Create Date: 2026-09-10 12:25:11.129324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656467a3bbd1'
down_revision: Union[str, Sequence[str], None] = '0ad174b21dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=3, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.Numeric(precision=3, scale=1),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
