"""Update tables

Revision ID: 731ca4679372
Revises: 3e70edd22b2b
Create Date: 2026-09-24 09:58:53.875481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '731ca4679372'
down_revision: Union[str, Sequence[str], None] = '3e70edd22b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор категории товаров',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='Название категории товара',
               existing_nullable=False)
    op.alter_column('categories', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор родительской категории товара',
               existing_nullable=True)
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Метка активности категории',
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор продукта',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Название товара',
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment='Описание товара',
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Стоимость товара',
               existing_nullable=False)
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(length=200),
               comment='Фотография товара',
               existing_nullable=True)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               comment='Количество товара',
               existing_nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Метка активности товара',
               existing_nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор категории товара из таблицы categories',
               existing_nullable=False)
    op.alter_column('products', 'seller_id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор продавца товара из таблицы users',
               existing_nullable=False)
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               comment='Рейтинг товара',
               existing_nullable=False)
    op.alter_column('reviews', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор отзыва',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор пользователя из таблицы users',
               existing_nullable=False)
    op.alter_column('reviews', 'product_id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор продукта из таблицы products',
               existing_nullable=False)
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               comment='Текст отзыва',
               existing_nullable=True)
    op.alter_column('reviews', 'comment_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата и время отзыва',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'grade',
               existing_type=sa.INTEGER(),
               comment='Оценка товара покупателем',
               existing_nullable=False)
    op.alter_column('reviews', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Метка активности отзыва',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор пользователя',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='Адрес электронной почты',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment='Захэшированный пароль',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Метка активности пользователя',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               comment='Роль пользователя',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Роль пользователя',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Метка активности пользователя',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Захэшированный пароль',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Адрес электронной почты',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор пользователя',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('reviews', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Метка активности отзыва',
               existing_nullable=False)
    op.alter_column('reviews', 'grade',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Оценка товара покупателем',
               existing_nullable=False)
    op.alter_column('reviews', 'comment_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата и время отзыва',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Текст отзыва',
               existing_nullable=True)
    op.alter_column('reviews', 'product_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор продукта из таблицы products',
               existing_nullable=False)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор пользователя из таблицы users',
               existing_nullable=False)
    op.alter_column('reviews', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор отзыва',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               comment=None,
               existing_comment='Рейтинг товара',
               existing_nullable=False)
    op.alter_column('products', 'seller_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор продавца товара из таблицы users',
               existing_nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор категории товара из таблицы categories',
               existing_nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Метка активности товара',
               existing_nullable=False)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Количество товара',
               existing_nullable=False)
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Фотография товара',
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Стоимость товара',
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Описание товара',
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Название товара',
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор продукта',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Метка активности категории',
               existing_nullable=False)
    op.alter_column('categories', 'parent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор родительской категории товара',
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Название категории товара',
               existing_nullable=False)
    op.alter_column('categories', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор категории товаров',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
