"""add orders and order_items

Revision ID: d7c75fd803ff
Revises: 731ca4679372
Create Date: 2026-09-29 08:43:48.782858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c75fd803ff'
down_revision: Union[str, Sequence[str], None] = '731ca4679372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор заказа'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Уникальный идентификатор пользователя из таблицы users'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус заказа'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Общая сумма заказа'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания заказа'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время обновления заказа'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный номер товара в заказе'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Уникальный номер заказа из таблицы orders'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Уникальный номер заказа из таблицы products'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество единиц одного вида товара'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Стоимомсть одного товара'),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Общая стоимость товара'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
